### ISSUE TITLE
Error in  RunDEtest

### ISSUE THREAD

**Issue by zjh0613** [zhanghao-njmu/SCP#100]
Hi, 
when I run follow  code 
NK<- RunDEtest(srt = NK, group_by = "celltype", fc.threshold = 1,only.pos = FALSE,norm.method = "LogNormalize")
I got a error
![image](https://user-images.githubusercontent.com/93072662/217992822-528be509-9da7-4121-b202-8319640fd2c7.png)
NK is a seurat object
![image](https://user-images.githubusercontent.com/93072662/217993018-768eb2b7-43cb-4c18-8955-f83babeda459.png)

**Comment by zhanghao-njmu** [comment]
This is a multithread problem, which means that at least one worker has died. This may be caused by errors in some of the previous runs. You can try restarting the current R session with `.rs.restartR()` and run your code again.
