### ISSUE TITLE
BiocParallel errors

### ISSUE THREAD

**Issue by ewowiredu** [zhanghao-njmu/SCP#102]
Hi @zhanghao-njmu 

This may be limited to my system but I have been trying to run the example using the pancreas_sub dataset. Everything works fine until **RunEnrichment**, **RunGSEA**, and **RunDynamicFeatures** which return **BiocParallel errors**. 

The issue occurs on my Macbook with M1 chip. I have tried it with iMACs with M1 and Intel chips and it works fine on both. Do you have an idea of what is going on and how to fix it? Thanks.

**Below are the codes and errors.**

pancreas_sub <- RunEnrichment( srt = pancreas_sub, group_by = "CellType", db = "GO_BP", species = "Mus_musculus", DE_threshold = "avg_log2FC > 1 & p_val_adj < 0.05" )

``
>[2023-02-23 00:53:38] Start Enrichment
>Threads used: 8
>Species: Mus_musculus
>Loaded cached db: GO_BP version:3.16.0 nterm:15992 created:2023-02-20 17:06:24
>Permform enrichment...
  |=================================================================================| 100%

>Error: BiocParallel errors
 > 5 remote errors, element index: 1, 2, 3, 4, 5
  >0 unevaluated and other errors
  >first remote error:
>Error: Operation not permitted

pancreas_sub <- RunGSEA(srt = pancreas_sub, group_by = "CellType", db = "GO_BP", species = "Mus_musculus", DE_threshold = "p_val_adj < 0.05" )

>[2023-02-23 01:11:56] Start GSEA
>Threads used: 8
>Species: Mus_musculus
>Loaded cached db: GO_BP version:3.16.0 nterm:15992 created:2023-02-20 17:06:24
>Permform GSEA...
 > |=====================================================================================| 100%

>|======================================================================================| 100%

>|======================================================================================| 100%
  >|=====================================================================================| 100%

>|======================================================================================| 100%

>|======================================================================================| 100%

>Error: BiocParallel errors
 > 5 remote errors, element index: 1, 2, 3, 4, 5
  >0 unevaluated and other errors
  >first remote error:
>Error: Operation not permitted

 pancreas_sub <- RunDynamicFeatures(srt = pancreas_sub, lineages = c("Lineage1", "Lineage2"), n_candidates = 200)

>[2023-02-23 01:15:52] Start RunDynamicFeatures
>Threads used: 8
>Calculating gene variances
>0%   10   20   30   40   50   60   70   80   90   100%
>[----|----|----|----|----|----|----|----|----|----|
>**************************************************|
>Calculating feature variances of standardized and clipped values
>0%   10   20   30   40   50   60   70   80   90   100%
>[----|----|----|----|----|----|----|----|----|----|
>**************************************************|
>Calculating gene variances
>0%   10   20   30   40   50   60   70   80   90   100%
>[----|----|----|----|----|----|----|----|----|----|
>**************************************************|
>Calculating feature variances of standardized and clipped values
>0%   10   20   30   40   50   60   70   80   90   100%
>[----|----|----|----|----|----|----|----|----|----|
>**************************************************|
>Number of candidate features(union): 225
>Calculate dynamic features for Lineage1...
>  |===                                 |   3%Stop worker failed with the error: wrong args for environment subassignment

>Error: BiocParallel errors
 > 5 remote errors, element index: 1, 2, 3, 4, 5
  >219 unevaluated and other errors
  >first remote error:
>Error: Operation not permitted
>Timing stopped at: 35.83 8.872 0.673

**Comment by zhanghao-njmu** [comment]
The important error message is `Error: Operation not permitted`. This may be caused by restricted execution or access permissions for some files. You can try the method in this article(https://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/), or search for other methods.

**Comment by ewowiredu** [comment]
Thanks, @zhanghao-njmu. Granting R and Rstudio full disk access did not help. I somehow got it working after reinstalling homebrew, llvm and gcc. Maybe I was missing some dependencies.
