### ISSUE TITLE
Error in 1:dim(data)[[1]] : argument of length 0

### ISSUE THREAD

**Issue by zzzSJTU** [zhanghao-njmu/SCP#106]
非常感谢大佬的R包！我在跑DynamicHeatmap的时候报错Error in 1:dim(data)[[1]] : argument of length 0，不知道是哪里出了问题想请教一下，谢谢！！
完整代码是：
ht <- DynamicHeatmap(
  srt = sce.all, lineages = c("Lineage1", "Lineage2"),
  use_fitted = TRUE, n_split = 6, reverse_ht = "Lineage1",
  species = "Homo_sapiens", db = c("GO_BP", "KEGG", "Reactome"), anno_terms = TRUE, anno_keys = TRUE, anno_features = TRUE,
  heatmap_palette = "viridis", cell_annotation = "seurat_clusters",
  separate_annotation = list("seurat_clusters", c("CD34", "MPO")), separate_annotation_palette = c("Paired", "Set1"),
  pseudotime_label = 25, pseudotime_label_color = "red",
  height = 5, width = 2
)
反馈：
[2023-03-04 20:17:43] Start RunDynamicFeatures
Workers: 14
Number of candidate features(union): 2
Calculate dynamic features for Lineage1...
  |============================================================================================================================| 100%

[2023-03-04 20:18:21] RunDynamicFeatures done
Elapsed time:37.91 secs
[2023-03-04 20:18:21] Start RunDynamicFeatures
Workers: 14
Number of candidate features(union): 2
Calculate dynamic features for Lineage2...
  |============================================================================================================================| 100%

[2023-03-04 20:19:01] RunDynamicFeatures done
Elapsed time:39.7 secs
Error in 1:dim(data)[[1]] : argument of length 0
In addition: Warning messages:
1: In serialize(data, node$con) :
  'package:stats' may not be available when loading
2: In serialize(data, node$con) :
  'package:stats' may not be available when loading
3: In serialize(data, node$con) :
  'package:stats' may not be available when loading
4: In serialize(data, node$con) :
  'package:stats' may not be available when loading

**Comment by zhanghao-njmu** [comment]
这个报错没能提供足够的信息，问题我暂时无法重复。因为DynamicHeatmap的参数比较多，我建议先逐一减少参数，测试是否还会继续报错。另外可以在相同环境下，先测试下DynamicHeatmap文档中的所有示例代码，检查下是否是环境问题。
最后有个建议，与这个报错无关，我注意到你想在anno_keys = TRUE和anno_features = TRUE的情况下同时做多个db富集分析，这会导致热图右侧的注释栏过长，建议加上参数db_combine=TRUE，这是SCPv0.4.0后新增的富集分析参数，可以将多个db合并，以简化分析和可视化。
希望能给你提供帮助！

**Comment by zzzSJTU** [comment]
加上参数db_combine=TRUE后解决，非常感谢！！

**Comment by zhanghao-njmu** [comment]
这个问题我还是需要再回答下。可能你的问题消失了，但实际上没有解决。我最终发现`Error in 1:dim(data)[[1]] : argument of length 0`这个错误的来源是Mfuzz包（DynamicHeatmap默认使用split_method=”mfuzz“）。Mfuzz的许多函数中都调用了`exprs`，但是没有明确`exprs`来自哪个包，默认应该是Biobase::exprs。然而当你library(rlang)后，将会使用rlang::exprs，这就导致Mfuzz发生错误。
