### ISSUE TITLE
RunSCVELO

### ISSUE THREAD

**Issue by namorosini** [zhanghao-njmu/SCP#109]
Hi, I'm trying to run the SCVelo but I'm facing the following error:

Error:SystemExit: None

How can I fix that?

Thanks!

**Comment by zhanghao-njmu** [comment]
Do you have spliced and unspliced assays in your Seurat object? If not, you need to generate and add them to your Seurat object using [velocyto](http://velocyto.org/velocyto.py/index.html).

**Comment by namorosini** [comment]
Thank you so much! It worked!

**Comment by zhanghao-njmu** [comment]
The error is caused by using base::t instead of Matrix::t, as base::t does not support transposing sparse matrices. SCP has already ensured that it internally calls Matrix::t since a long time ago, so please make sure that you are using the latest version of SCP.
@qindan2008

**Comment by denvercal1234GitHub** [comment]
Hi @zhanghao-njmu @namorosini , I was able to convert my concatenated looms of different samples into 1 in Python and converted that to Seurat object. Would you mind helping me to add the spliced and unsliced (and any other info needed) from my loom-converted Seurat object to my GEX Seurat object in R? Thanks so much!
