### ISSUE TITLE
RunPAGA with pancreas_sub occurred error；and RunSCVELO  with pancreas_sub occurred error

### ISSUE THREAD

**Issue by DocMonster77** [zhanghao-njmu/SCP#126]
pancreas_sub <- RunPAGA(srt = pancreas_sub, group_by = "SubCellType", linear_reduction = "PCA", nonlinear_reduction = "UMAP")
'misc' slot is not converted.
'tools' slot is not converted.
Error in match.arg(arg = layer, choices = Layers(object = object, search = FALSE)) : 
  'arg' should be one of “counts”, “data”, “scale.data”

**Comment by DocMonster77** [comment]
pancreas_sub <- RunSCVELO(
+   srt = pancreas_sub, group_by = "SubCellType",
+   linear_reduction = "PCA", nonlinear_reduction = "UMAP"
+ )
'misc' slot is not converted.
'tools' slot is not converted.
Filtered out 12123 genes that are detected 30 counts (shared).
Normalized count data: X, spliced, unspliced.
Logarithmized X.
computing neighbors
    finished (0:00:00) --> added 
    'distances' and 'connectivities', weighted adjacency matrices (adata.obsp)
computing moments based on connectivities
    finished (0:00:01) --> added 
    'Ms' and 'Mu', moments of un/spliced abundances (adata.layers)
computing velocities
    finished (0:00:00) --> added 
    'stochastic', velocity vectors for each individual cell (adata.layers)
computing velocity graph (using 1/12 cores)
Error in match.arg(arg = layer, choices = Layers(object = object, search = FALSE)) : 
  'arg' should be one of “counts”, “data”, “scale.data”

**Comment by Yuuuushan** [comment]
I have the same question using RunSCVELO. Did you solve it?

**Comment by a347045077** [comment]
I have also meet the same question using RunSCVELO, How to solve it?

**Comment by realzehuali** [comment]
I have also met the same question using RunSCVELO and RunPAGA, How to solve it?

**Comment by jerryzuo0214** [comment]
Detail:  After a through debug, I have located the bug at SeuratObject::AddMetadata as well as SeuratObject::LayerData under Seurat main Version 5, the underlying bug of above two functions caused this issue.
Bug Location:   Unless the author change the Metadata embedding approach of SCP::adata_to_srt() [   --Line89: srt[["RNA"]] <- AddMetaData(srt[["RNA"]], metadata = as.data.frame(py_to_r_auto(adata$var)))   ] , the issue might continue to appear. 

Solution: A compromise is to downgrade Seurat to 4.3.1 via install.packages("Seurat") and downgrade the SeuratObject via remotes::install_github("mojaveazure/seurat-object")

**Comment by jerryzuo0214** [comment]
As I mentioned above, the main version transition have caused many parameters' change in some functions, and LayerData will use layer-parameter instead of slot-parameter in the future, even though I do not have time to dig out the underlying conflict of the parameters' transition, there just true that the issue solved when I downgrade the Seurat as well as SeuratObject.

**Comment by zhanghao-njmu** [comment]
Apologies for the delayed response. Currently, SCP only supports Seurat v4. However, I will definitely consider adding support for Seurat v5 once it has a stable release. It's important to stay updated with the latest versions of packages to ensure compatibility and take advantage of new features. If you have any other questions or need further assistance, please let me know.

**Comment by Jzwing** [comment]
I changed Seruat v5(Automaticly installed by SCP  Env_ solution ), I reinstalled it with Seuart V4, But when I library(SCP) 
Error: package or namespace load failed for ‘SCP’: object ‘LayerData<-’ is not exported by 'namespace:SeuratObject'
How to fix this?

**Comment by jerryzuo0214** [comment]
> I changed Seruat v5(Automaticly installed by SCP  Env_ solution ), I reinstalled it with Seuart V4, But when I library(SCP) 
> Error: package or namespace load failed for ‘SCP’: object ‘LayerData<-’ is not exported by 'namespace:SeuratObject'
> How to fix this?

Due to the version matching issue，you likely have installed a higher version of SeuratObject，thus a downgrade might be helpful.
