### ISSUE TITLE
Failed to install package

### ISSUE THREAD

**Issue by Phoenix12580** [zhanghao-njmu/SCP#131]
Hi,

I tried to install this beautiful package,but failed how can i fix it? My R version is 4.2.1 64bit

Thank you very much

![image](https://user-images.githubusercontent.com/55424563/236848703-f3c99ca5-4042-46cc-8e38-17288c0e9a25.png)

Error: package or namespace load failed for 'SCP' in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Program Files/R/R-4.2.1/library/00LOCK-SCP-main/00new/SCP/libs/x64/SCP.dll':
  LoadLibrary failure:  %1 不是有效的 Win32 应用程序。

**Comment by TaoGuo1998** [comment]
I have also met the same problem. Have you resolved it?

**Comment by TaoGuo1998** [comment]
My R version is 4.2.2 64bit

**Comment by zhanghao-njmu** [comment]
This bug has been fixed in SCP v0.5.1
