### ISSUE TITLE
ERROR: dependency ‘harmony’ is not available for package ‘SCP’

### ISSUE THREAD

**Issue by Kiliankleemann** [zhanghao-njmu/SCP#14]
Tried installing SCP with devtools. I have python 3.10

**Comment by zhanghao-njmu** [comment]
I found that ‘harmony’ was removed from the CRAN repository recently. You can install it manually from GitHub.
```
library(devtools)
install_github("immunogenomics/harmony")
```
In the next SCP version, I will move the "harmony" to the Remote dependencies.
Thanks! @Kiliankleemann
