### ISSUE TITLE
Error in devtools::install_local('SCP-main.zip')：Error: package or namespace load failed for 'SCP' in inDL(x, as.logical(local), as.logical(now), ...):  unable to load shared object 'D:/R-4.2.2/library/00LOCK-SCP-main/00new/SCP/libs/x64/SCP.dll':   LoadLibrary failure:  %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by zhangdae** [zhanghao-njmu/SCP#147]
> devtools::install_local('SCP-main.zip')
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                    
2: CRAN packages only                     
3: None                                   
4: ggtree (3.4.0 -> b51cece3b...) [GitHub]

Enter one or more numbers, or an empty line to skip updates: 4
ggtree (3.4.0 -> b51cece3b...) [GitHub]
Downloading GitHub repo YuLab-SMU/ggtree@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                     
2: CRAN packages only                      
3: None                                    
4: treeio (1.22.0 -> a83c6c146...) [GitHub]

Enter one or more numbers, or an empty line to skip updates: 4
treeio (1.22.0 -> a83c6c146...) [GitHub]
Downloading GitHub repo GuangchuangYu/treeio@HEAD
* installing *source* package 'treeio' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (treeio)
* installing *source* package 'ggtree' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (ggtree)
* installing *source* package 'SCP' ...
** using staged installation
** libs
g++ -std=gnu++11 -shared -s -static-libgcc -o SCP.dll tmp.def RcppExports.o asMatrix.o -LD:/rtools42/x86_64-w64-mingw32.static.posix/lib/x64 -LD:/rtools42/x86_64-w64-mingw32.static.posix/lib -LD:/R-4.2.2/bin/x64 -lR
collect2.exe: error: ld returned 5 exit status
installing to D:/R-4.2.2/library/00LOCK-SCP-main/00new/SCP/libs/x64
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'SCP' in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'D:/R-4.2.2/library/00LOCK-SCP-main/00new/SCP/libs/x64/SCP.dll':
  LoadLibrary failure:  %1 不是有效的 Win32 应用程序。

**Comment by zhangdae** [comment]
solved this problem by using   devtools::install_local('SCP-0.3.0.tar.gz')......WTF

**Comment by zhanghao-njmu** [comment]
You can try downloading and installing [SCPv0.5.1](https://github.com/zhanghao-njmu/SCP/archive/refs/tags/v0.5.1.tar.gz).

**Comment by huanwudi123** [comment]
已经解决这个问题了，感谢大佬亲自发邮件！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月14日(周四) 下午4:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhanghao-njmu/SCP] Error in devtools::install_local('SCP-main.zip')：Error: package or namespace load failed for 'SCP' in inDL(x, as.logical(local), as.logical(now), ...):  unable to load shared object 'D:/R-4.2.2/library/00LOCK-SCP-main/00new/SCP/libs/x64/SCP.dll':   LoadLibrary failure:  %1 不是有效的 Win32 应用程序。 (Issue #147)




 
You can try downloading and installing SCPv0.5.1.
