### ISSUE TITLE
EnrichmentPlot，plot_type “network” and "enrichmap" are unavailable"

### ISSUE THREAD

**Issue by Githubxsw** [zhanghao-njmu/SCP#155]
EnrichmentPlot(srt = pancreas_sub, group_by = "celltype", group_use = "Basal1",plot_type = "network")
EnrichmentPlot(srt = pancreas_sub, group_by = "CellType", group_use = "Basal1",plot_type = "enrichmap")

Error in match.arg(plot_type) :    'arg' should be one of “bar”, “lollipop”, “wordcloud”, “comparison”，

 “network” and "enrichmap" are unavailable"

How I can update the SCP?

**Comment by zhanghao-njmu** [comment]
You only need to download and install the latest version of SCP(v0.5.1) by running the command `devtools::install_github("zhanghao-njmu/SCP")`

**Comment by zhanghao-njmu** [comment]
Can you reinstall the latest SCP and try again? This issue may have been resolved in the latest version. If it still persists, please let me know.

**Comment by Githubxsw** [comment]
> You only need to download and install the latest version of SCP(v0.5.1) by running the command `devtools::install_github("zhanghao-njmu/SCP")`

Thank you. It does work.
