### ISSUE TITLE
db "WikiPathway" Cannot Download Successful

### ISSUE THREAD

**Issue by Minazukiz** [zhanghao-njmu/SCP#202]

**Comment by zhanghao-njmu** [comment]
The file format of the WikiPathways database has recently been adjusted, and SCP has been updated to be compatible with this change in the new version. Please update to version 0.5.5 and try again. 
Note that SCP currently only supports Seurat V4 and SeuratObject V4. Do not update them when updating SCP, as compatibility with their v5 versions will be added in the future.

**Comment by Minazukiz** [comment]
> The file format of the WikiPathways database has recently been adjusted, and SCP has been updated to be compatible with this change in the new version. Please update to version 0.5.5 and try again. Note that SCP currently only supports Seurat V4 and SeuratObject V4. Do not update them when updating SCP, as compatibility with their v5 versions will be added in the future.

Thanks a million！
