### ISSUE TITLE
Error running scVelo and PAGA

### ISSUE THREAD

**Issue by bapoorva** [zhanghao-njmu/SCP#21]
Hi,

I have a single cell dataset that was processed using Seurat. So my suerat object has an SCT assay well and the dimensions are different from the RNA assay. When i run `RunPAGA` or `RunSCVELO`, I'm getting the following error.

```
>scrna <- RunPAGA(
  srt = scrna, group_by = "var_cluster",
  linear_reduction = "PCA", nonlinear_reduction = "UMAP", return_seurat = TRUE
)
Assay 'SCT' is in the srt object but not converted.
Assay 'ambiguous' is in the srt object but not converted.
Error in py_set_attr_impl(x, name, value) : 
  ValueError: Value passed for key 'spliced' is of incorrect shape. Values of layers must match dimensions (0, 1) of parent. Value had shape (7227, 18401) while it should have had (7227, 55361).
  ```
  
Can you help me out with this please ?

**Comment by zhanghao-njmu** [comment]
RunPAGA or RunSCVELO use the "RNA" assay as an "X" matrix in [anndata ](https://anndata.readthedocs.io/en/latest/generated/anndata.AnnData.html)by default. 
I found that your "spliced" assay has 18401 features, which may be a subset of the full features in the "RNA" assay.
If these features are the same as in the SCTassay, then you can specify assay_X="SCT"

**Comment by zhanghao-njmu** [comment]
I found that feature numbers being different between assays would cause the adata conversion to fail. In the latest version, I have solved this problem. And added the example of SCT assay for scvelo. Please refer to the `RunSCVELO` documentation. @bapoorva

**Comment by Sa753** [comment]
Hi Zhanghaoe,

I have the same problem I have an integrated Seurat object with spliced and unspoiled counts but those counts are not similar to the counts in the RNA or SCT assays?. I am not sure if they should be similar or not as they are produced from different processing for example spliced and unspoiled were run on the fastq files but there are filtering steps to obtain the the counts in the RNA or SCT assays so I don't think they are expected to be similar. Is there anything I can do please?
hanks
