### ISSUE TITLE
 miniconda installation failed [exit code 2]

### ISSUE THREAD

**Issue by Organacids** [zhanghao-njmu/SCP#228]
SCP::PrepareEnv()
Conda not found. Installing miniconda...
* Installing Miniconda -- please wait a moment ...
Error: miniconda installation failed [exit code 2]

**Comment by sfortier32** [comment]
You need to go to miniconda's download page and install it on your computer, then try running SCP::PrepareEnv() again.

**Comment by Organacids** [comment]
Thank you and I will try it again
