### ISSUE TITLE
Slingshot Warning

### ISSUE THREAD

**Issue by wangtanzhang612** [zhanghao-njmu/SCP#237]
Hi, I recently encountered the following warning messages, which prevent Slingshot from outputting lineage images.

CellDimPlot(sce, group.by = "celltype", reduction = "UMAP", lineages = paste0("Lineage", 1:2), lineages_span = 0.1)
Warning messages:
1: No shared levels found between `names(values)` of the manual scale and the
data's fill values. 
2: No shared levels found between `names(values)` of the manual scale and the
data's fill values.

**Comment by EddieLv** [comment]
Me  too! And I found that the error comes from get_legend() in CellDimPlot(). So if you set 'stat.by', 'lineages' or 'paga' in CellDimPlot(), there will be no image!

**Comment by EddieLv** [comment]
Oh, I just solved it through modifying the source code of SCP and reinstall it through devtools::install_local.
grobIndex <- which(grepl("guide-box", grob_names))
                                          to
grobIndex <- which(grepl("guide-box-bottom", grob_names))

**Comment by EddieLv** [comment]
@zhanghao-njmu Hope you can repair this bug!

**Comment by wangtanzhang612** [comment]
@EddieLv Thx!!

**Comment by XiaolongYang-HZAU** [comment]
有相同的问题，希望作者可以将这个修复加入最新版的安装包

**Comment by zccovo** [comment]
有相同的问题，希望作者可以将这个修复加入最新版的安装包
