### ISSUE TITLE
Heatmap - selective row labeling even when show_row_names set to FALSE

### ISSUE THREAD

**Issue by bapoorva** [zhanghao-njmu/SCP#248]
Hi,

Great package. I had a question about the GroupHeatmap function. 

The function generates a heatmap with only some rows labelled when show_row_names =F and when I set it to show_row_names=T, it gives me rownames twice. How do i remove the selective labeling on the left ?

![sample_heatmap](https://github.com/user-attachments/assets/2d3f25dc-022a-425c-b8c1-ec09d1b9619a)

Thanks

**Comment by Morriseylab** [comment]
Looks like a bug. I was able to hack the code to get what I needed.

basically commented out one line 

```
if (is.null(ha_left)) {
      #ha_left <- ha_mark
    } else {
      ha_left <- c(ha_mark, ha_left)
    }
  }
  ```

**Comment by bapoorva** [comment]
Looks like a bug. I was able to hack the code to get what I needed.

basically commented out one line 

```
if (is.null(ha_left)) {
      #ha_left <- ha_mark
    } else {
      ha_left <- c(ha_mark, ha_left)
    }
  }
  ```
