### ISSUE TITLE
Error running scVelo and PAGA error related to issue #21 

### ISSUE THREAD

**Issue by Sa753** [zhanghao-njmu/SCP#26]
Hi Zhanghaoe,

I have the same problem I have an integrated Seurat object with spliced and unspoiled counts but those counts are not similar to the counts in the RNA or SCT assays?. I am not sure if they should be similar or not as they are produced from different processing for example spliced and unspoiled were run on the fastq files but there are filtering steps to obtain the the counts in the RNA or SCT assays so I don't think they are expected to be similar. Is there anything I can do please?
hanks

**Comment by zhanghao-njmu** [comment]
"RNA" assay is used to do dimension reduction, generate neighbor graphs, and cluster cells.
"spliced" and "unspliced" assays are only used to calculate cell velocity.
"RNA", "spliced", or "unspliced" assay in the same Seurat object should have the same number of features. 
However, the number of features of the "SCT" assay is generally reduced. 
When running scVelo or PAGA, older versions of SCP will not be able to convert Seurat objects to Anndata objects if the number of features between assays is different. You can update to the latest version of SCP **(v0.2.3)** and retry.

**Comment by Sa753** [comment]
Hi Zhang,
I have reinstalled the package to version 0.2.3 but still not working. I never got equal number of spliced and unspoiled counts and they are not the same number as the counts in SCT.
I convert the loom file which is the output from Velocyto to seurat object then I process this object by filtering low quality cells then SCT and then integration with other samples so I don't have similar counts even before integration as the SCT counts are never similar to spliced counts. Am I doing something wrong here?
Thanks

**Comment by zhanghao-njmu** [comment]
From your description it looks like the steps are correct. You need to provide more information about the error.

**Comment by Sa753** [comment]
I have copied and pasted the code I used and I am trying here an object without integration to make it easier. I have 4 assays in the seurat object SCT, spliced, unspliced and ambiguous. the SCT is run on the 'spliced' counts as in seurat tutorial in the link above which explains the error that I got below but I am not sure what to do. is it an option to remove the features that are not in the 3 assays by removing genes or rows from the matrix. Is that advised or will mess up the data? what would be the code for that?.

Let me know if you need more info as I am keen to use it


> velo <- RunSCVELO(
+ srt = velo, group_by = "seurat_clusters",
+ linear_reduction = "PCA", nonlinear_reduction = "UMAP", return_seurat = TRUE)
Error: Cannot find 'RNA' in this Seurat object
> velo <- RunSCVELO(
+ srt = velo, group_by = "seurat_clusters",
+ linear_reduction = "PCA", nonlinear_reduction = "UMAP", return_seurat = TRUE, assay_X = 'SCT')
Error in srt_to_adata(srt = srt, assay_X = assay_X, slot_X = slot_X, assay_layers = assay_layers,  : 
  Matrix in assay 'unspliced' should contain the same features with assay 'SCT'

**Comment by zhanghao-njmu** [comment]
It seems that feature names of the **unspliced** assay does not match the **SCT**. Can you show the top feature names with `head(rownames(velo[["SCT"]]))` and `head(rownames(velo[["unspliced"]]))`? You can also check it by `all(rownames(velo[["unspliced"]]) %in% rownames(velo[["SCT"]]))`.

**Comment by Sa753** [comment]
The SCT will not be similar to the unsliced counts and that is because the assay that the SCT has been run on was the 'spliced' so SCT picked up the genes that make the difference from the spliced assay but not unspliced, if that makes sense

**Comment by Sa753** [comment]
Hi Zhang,

I found out the cause for the discrepancy. I did a filtering step for low expressed genes when I converted loom to seurat which messed up the spliced and unspliced counts as it removed different number of genes from each matrix so they became not having same features hence the error message. I should not do filtering of low expressed genes as it. 
You can now close this issue. 
Thanks
