### ISSUE TITLE
Install error 'OPENSSL_3.0.0' not found

### ISSUE THREAD

**Issue by zy-fang** [zhanghao-njmu/SCP#28]
Hi,

Thanks for open sourcing this code. I would love to be able to use the codes.

While I installed the packages, 
'''
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/anaconda3/envs/R4.2/lib/R/library/HDF5Array/libs/HDF5Array.so':
 /anaconda3/envs/R4.2/lib/R/library/rhdf5/libs/../../../../libcrypto.so.1.1: version `OPENSSL_3.0.0' not found (required by /anaconda3/envs/R4.2/lib/R/library/HDF5Array/libs/HDF5Array.so)

Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
'''
I found my envs has OPENSSL_1.0.0 installed.
May I ask which version of R you tested this under ?

**Comment by zhanghao-njmu** [comment]
This looks like a problem with the conda environment.
You can check the openssl version in your conda environment with `conda list openssl`.
HDF5Array can probably be installed into your conda R via `conda install -c bioconda bioconductor-hdf5array`.
If none of these work, I recommend disabling the conda environment and conda R, and installing R and related packages in your system environment.

**Comment by zhanghao-njmu** [comment]
I have moved the packages that are less used to "Suggestions" and will not be installed when installing SCP. You can try to install this latest version of SCP (v0.2.3). @zy-fang
