### ISSUE TITLE
 could not find function "PrepareVirtualEnv"

### ISSUE THREAD

**Issue by DRSEI** [zhanghao-njmu/SCP#3]
This is really great pakage thank you @zhanghao-njmu . Howevere I am unable to run  PrepareVirtualEnv commend. .
```
PrepareVirtualEnv(python = py, pipy_mirror = "https://pypi.tuna.tsinghua.edu.cn/simple", remove_old = TRUE)
Error in PrepareVirtualEnv(python = py, pipy_mirror = "https://pypi.tuna.tsinghua.edu.cn/simple",  : 
  could not find function "PrepareVirtualEnv"
```

I belove this is due to above issue am i right ?
`Error: object 'ExpHeatmapPlot' not found`

Could you advise me how can i fix this?

**Comment by zhanghao-njmu** [comment]
You may be using an older version of SCP. You can try reinstalling the latest version and running SCP::PrepareVirtualEnv() in a new R session.

**Comment by DRSEI** [comment]
Thank you @zhanghao-njmu . I managed to install it but now i am having other issue. 


When i run the below code. I am getting error. 

```
DEGs <- pancreas1k@tools$DEtest_CellType$AllMarkers_wilcox
DEGs <- DEGs[with(DEGs, avg_log2FC > 1 & p_val_adj < 0.05), ]
ht <- ExpHeatmap(
  srt = pancreas1k, features = DEGs$gene, feature_split = DEGs$group1, cell_split_by = "CellType",
  species = "Mus_musculus", anno_terms = TRUE, anno_keys = TRUE, anno_features = TRUE,
  row_title_size = 0, height = 5, width = 7
)
print(ht$plot)
```



```
Species: Mus_musculus
Loaded cached db: GO_BP version:3.15.0 nterm:15985 created:2022-10-13 21:59:58
Permform enrichment...
  |                                                                                                                                                 |   0%Error in reducer$value.cache[[as.character(idx)]] <- values : 
  wrong args for environment subassignment

thread_monitor No such process in pthread_detach
> 
```

**Comment by zhanghao-njmu** [comment]
Enrichment analysis in SCP calls the available threads by default via `BiocParallel::bpparam()` to speed up the computation. The error seems to be a problem with BiocParallel (Bioconductor/BiocParallel#206, Bioconductor/BiocParallel#189, Bioconductor/BiocParallel#177). 

I was unable to reproduce this error in my environment.  You can try to :
1. Upgrade to the latest version of BiocParallel.
2. Disable parallelization by `BiocParallel::register(BiocParallel::SerialParam(), default = TRUE)` before running ExpHeatmap or other functions that use parallelization.

Finally, you can also try running it on a different computer to see if it's an environment problem.
