### ISSUE TITLE
Error on `adata_to_srt` function

### ISSUE THREAD

**Issue by joonan30** [zhanghao-njmu/SCP#70]
Hi, 

Thanks for the nice tool. I am trying to convert an anndata object to a seurat object. The ANN file `Processed_data_ATAC_processed-count-data.h5ad` was downloaded from https://console.cloud.google.com/storage/browser/neuro-dev/Processed_data;tab=objects?pli=1&prefix=&forceOnObjectsSortingFiltering=false 

```
sc <- import("scanpy")

adata <- sc$read_h5ad("Processed_data_ATAC_processed-count-data.h5ad")
```

It gave me

```
Error in validObject(.Object) : 
  invalid class “DimReduc” object: invalid object for slot "cell.embeddings" in class "DimReduc": got class "data.frame", should be or extend class "matrix"
```

Do you have any clue on this error?

Thanks,

**Comment by zhanghao-njmu** [comment]
Thanks for reporting the issue. This is a bug in the `adata_to_srt` function. I found that sometimes adata.obsm can be a `data.frame` instead of a `matrix`; However, Seurat requires that cell embeddings are of class `matrix`. I fixed this bug in version 0.2.6 and tested it successfully on the file you provided. You can update the SCP and retry.

**Comment by joonan30** [comment]
Thanks Hao for the prompt update!! It works well.

**Comment by mushan-guan** [comment]
I ran into this problem when I used adata_to_srt function

Thanks for your help

```markdown
```r
> adata
AnnData object with n_obs × n_vars = 2355 × 13152
    obs: 'in_tissue', 'array_row', 'array_col', 'sample', 'leiden', '_indices', '_scvi_batch', '_scvi_labels', 'Mg.1', 'Mg.2', 'Tumor cell.1', 'OLC', 'Tumor cell.2', 'Mono/Mac/DC', 'Neu.1', 'Neu.2', 'abT', 'gdT', 'B cell', 'MZB', 'Unknown'
    var: 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std', 'MT_gene'
    uns: '_scvi_manager_uuid', '_scvi_uuid', 'hvg', 'leiden', 'leiden_colors', 'log1p', 'mod', 'neighbors', 'pca', 'sample_colors', 'spatial', 'umap'
    obsm: 'MT', 'X_pca', 'X_pca_harmony', 'X_umap', 'means_cell_abundance_w_sf', 'q05_cell_abundance_w_sf', 'q95_cell_abundance_w_sf', 'spatial', 'stds_cell_abundance_w_sf'
    varm: 'PCs'
    layers: 'counts', 'scaled'
    obsp: 'connectivities', 'distances'

srt <- adata_to_srt(adata)
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent

**Comment by Qtasnim** [comment]
Hello, 

I also have a problem with this, but I get a different error:

`> srt <- adata_to_srt(adata)
Error in slot(object = object, name = "features")[[layer]] <- features : 
  more elements supplied than there are to replace`

The seurat to anndata worked beautifully, but then I did PAGA analysis and now I want to convert back. 
Do you have any idea how can I solve this? 

Thanks.
