### ISSUE TITLE
Error on RunSCVELO function

### ISSUE THREAD

**Issue by joonan30** [zhanghao-njmu/SCP#76]
Hi,

I've got an error on RunSCVELO:

```
d2 <- RunSCVELO(srt = d2, group_by = "groups", linear_reduction = "PCA", nonlinear_reduction = "UMAP")
'misc' slot is not converted.
'tools' slot is not converted.
Error in py_call_impl(callable, dots$args, dots$keywords) :
numpy.AxisError: axis 1 is out of bounds for array of dimension 1
```

It seems something happened in numpy via reticulate but cannot point out what the cause was.. 

Thanks,

**Comment by zhanghao-njmu** [comment]
When calculating RNA velocity, you need to provide a Seurat object containing both "spliced" and "unspliced" assays.

**Comment by joonan30** [comment]
Thanks!!
