### ISSUE TITLE
Few questions/issues with SCP

### ISSUE THREAD

**Issue by abbaslab** [zhanghao-njmu/SCP#81]
Hoping to get your help on few issues in SCP:

1) Can pathway enrichment be done for other than GO_BP? Seems GO_Bp is only option and couldn't find in description if other pathways can be tested

2) When running “pancreas_sub <- RunCellQC(srt = pancreas_sub)  this results in list of cells that “failed” versus those that passed. Does the new Seurat object contain only those that passed the QC? Or do we have to add additional step to subset? 

3) ExpHeatmap function:
a.	Issues with figure dimensions and outputting as png in good size. Tried different settings but the proportions are always way off. 
b.	How to choose a db other than GO_BP
c.	I don’t think its showing all the cells as columns. We hav 24,000 in the object but the output seems to show much less.

4) RunGSEA: does this function take only the differentially genes? Or the whole ranked list (i.e. any gene detected with any p value?))

5) RunEnrichment: is GO_BP the only database?

6) DynamicHeatmap: 
Error in DynamicHeatmap(srt = del7, lineages = c("Lineage1", "Lineage2"),  : 
  No dynamic features found in the meta.data or in the assay: RNA

However, my object has Lineage1 and lineage2 and I had already run the slingshot and RunDynamicFeatures without error. I get 2 lineages

Thanks much!

**Comment by zhanghao-njmu** [comment]
1. Yes. All enrichment analysis functions of SCP, such as `RunEnrichment`, `RunGSEA` or `GroupHeatmap`, support other databases than GO_BP as input. The following databases are currently supported for automatic construction using the `PrepareDB` function, including "GO_BP", "GO_CC", "GO_MF", "KEGG", "WikiPathway", "Reactome", "ProteinComplex", "DGI", "MP", "DO", "PFAM", "Chromosome", "GeneType", "Enzyme", "TF", "SP", "CellTalk", "CellChat". The latest version of SCP also supports database construction using the data on hand. See the documentation of the `PrepareDB` function for details.
2. RunCellQC does not delete any cells, it only adds the QC results to the `meta.data` of the Seurat object. You can view it via `srt[["CellQC"]]`. Based on the results you can manually filter out the high-quality cells by `srt[,srt$CellQC=="Pass"]`
3. a. You can try to adjust the `width` and `height` parameters in the heatmap to control the size of the heatmap body. You can also use `panel_fix(ht$plot,height,width)` to adjust the overall size after the drawing is done.
b. The `db` parameter in the Heatmap function specifies the database to be used for enrichment analysis
c. Yes. ExpHeatmap will control the number of cells shown in each group with the `max_cells` parameter. The default value is 100.
4. The examples use differential genes with `padj < 0.05`, while the `RunGSEA` and `RunEhrichment` functions themselves have no requirement for genes and can specify inputs without having to run RunDEtest beforehand. See the documentation of the `RunGSEA` and `RunEnrichment` functions for details.
5. The `db` parameter specifies the database to be used for enrichment analysis
6. First ensure that the developmental trajectory of the cells is continuous. The genes used for visualization are filtered according to the thresholds `min_expcells = 20, r.sq = 0.2, dev.expl = 0.2, padjust = 0.05`. These parameters are adjustable in `DynamicHeatmap`. You can also check the results of `RunDynamicFeatures` manually, saved in `srt@tools$DynamicFeatures_Lineage1$DynamicFeatures`. Finally you can increase the `n_candidates` in `RunDynamicFeatures` to calculate more genes.
