### ISSUE TITLE
Some functions not found

### ISSUE THREAD

**Issue by wbf520qcp** [zhanghao-njmu/SCP#83]
I have problems with some functions and want to seek your opinions. I installed SCP from Github and ran some examples. However, some functions are not supported, e.g. could not find function "GroupHeatmap". 

Thank you!

**Comment by zhanghao-njmu** [comment]
You should first make sure that you have the latest version of SCP installed. If not, you can reinstall it and try to run it again

**Comment by wbf520qcp** [comment]
Yes, I just reinstalled today

**Comment by zhanghao-njmu** [comment]
That's strange. You may restart your r session and retry. The function code can also be viewed with `SCP::GroupHeatmap`.

**Comment by wbf520qcp** [comment]
I got this error when loading the package Error: lazy-load database '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/SCP/R/SCP.rdb' is corrupt

**Comment by zhanghao-njmu** [comment]
You need to restart your R session and then library(SCP)

**Comment by wbf520qcp** [comment]
Thanks, it worked. Another issue, when I plot DEGs (ExpHeatmap) and set feature_split = DEGs$group1, I got Error: names of `text` should have overlap to levels in `align_to`. The my group.by variable has the exact same levels as in DEGs$group1. It worked fine if I remove   feature_split = DEGs$group1, but that didn't give me pathways for each group.
<img width="896" alt="Screen Shot 2023-01-05 at 11 55 28 PM" src="https://user-images.githubusercontent.com/56213252/210939331-c8b2fdda-158c-4b74-af6b-56540b7f40b8.png">

**Comment by zhanghao-njmu** [comment]
It seems that some enrichment results were filtered, but there is no way to know exactly what happened because I cannot duplicate this problem. However, I have added some code to make sure this type of error does not happen again. You can install the latest version of SCP(0.2.6.9002) and try again.
