### ISSUE TITLE
scp::ExpDimPlot

### ISSUE THREAD

**Issue by zjh0613** [zhanghao-njmu/SCP#88]
Hi developer
I wonder if SCP::ExpDimPlot has parameters like min.cutoff and max.cutoff in seruat::featureplot.

**Comment by zhanghao-njmu** [comment]
`ExpDimPlot` has similar parameters, `lower_quantile` and `upper_quantile`, to set the upper and lower limits of expression for each feature according to the quantile. 

In addition to these two parameters, SCP after **version 0.2.7** has `lower_cutoff` and `upper_cutoff` to set limits on the expressions of all features.

In addition, the `keep_scale` parameter can also be used to control the range of the colorbar.

The following is an example of ExpDimPlot for SCP **version 0.2.7**:
```
data("pancreas_sub")
pancreas_sub <- Standard_SCP(pancreas_sub)
ExpDimPlot(pancreas_sub, c("Ins1", "Gcg", "Sst", "Ghrl"), reduction = "UMAP")
```
![image](https://user-images.githubusercontent.com/24678781/213110534-2c89866e-78ff-43dd-8121-9ec44a48f901.png)

`ExpDimPlot(pancreas_sub, c("Ins1", "Gcg", "Sst", "Ghrl"), reduction = "UMAP", lower_quantile = 0, upper_quantile = 0.8)`
![image](https://user-images.githubusercontent.com/24678781/213110678-e1194bbb-570a-44d5-bde8-2b11ae4e3d04.png)

`ExpDimPlot(pancreas_sub, c("Ins1", "Gcg", "Sst", "Ghrl"), reduction = "UMAP", lower_cutoff = 1, upper_cutoff = 4)`
![image](https://user-images.githubusercontent.com/24678781/213110786-8197dd42-9305-4034-9fa3-47a67fe51fbe.png)

`ExpDimPlot(pancreas_sub, c("Ins1", "Gcg", "Sst", "Ghrl"), reduction = "UMAP", bg_cutoff = 1, lower_cutoff = 1, upper_cutoff = 4)`
![image](https://user-images.githubusercontent.com/24678781/213110908-f855aa4c-dcbf-4061-a101-d01be7da7b21.png)

`ExpDimPlot(pancreas_sub, c("Ins1", "Gcg", "Sst", "Ghrl"), reduction = "UMAP", keep_scale = "all")`
![image](https://user-images.githubusercontent.com/24678781/213110982-c8f72c5f-03f1-4568-805f-c113ee7898ab.png)

`ExpDimPlot(pancreas_sub, c("Sst", "Ghrl"), split.by = "Phase", reduction = "UMAP", keep_scale = "feature")`
![image](https://user-images.githubusercontent.com/24678781/213111084-a871f07a-3fd3-4446-bee7-072aef2b74f4.png)
