### ISSUE TITLE
Error installing and compiling

### ISSUE THREAD

**Issue by TheBorgy** [zhanghao-njmu/SCP#9]
Hi,

Thank you for creating this very promising resource! I would love to be able to use and test the package. I keep running into the error below when I install SCP per the documentation instructions using: 

>  if (!require("devtools", quietly = TRUE)) {
>   install.packages("devtools")
> }
> devtools::install_github("zhanghao-njmu/SCP")

I tried installing scmap using bioconductor but the error persisted. Any idea or recommendation that might be causing this?

> ERROR: dependency ‘scmap’ is not available for package ‘SCP’
> * removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/SCP’
> Warning messages:
> 1: In i.p(...) : installation of package ‘scmap’ had non-zero exit status
> 2: In i.p(...) :
>   installation of package ‘/var/folders/y5/6jm834dx4l1ddxtcsnjyrf2r0000gp/T//Rtmp72LD66/filee033c8d1512/SCP_0.2.0.tar.gz’ had non-zero exit status

**Comment by zhanghao-njmu** [comment]
[scmap](https://bioconductor.org/packages/release/bioc/html/scmap.html) is a Bioconductor package. You can try to install it manually from Bioconductor:
```
options(repos = BiocManager::repositories())
BiocManager::install("scmap")
```
Or install from GitHub:
```
install.packages("devtools")
devtools::install_github("hemberg-lab/scmap")
```

**Comment by zhanghao-njmu** [comment]
If the installation of SCP fails, or if there are some conflicting versions of R packages, you can use renv to install SCP in an isolated R environment. See the readme for installation methods. @TheBorgy
